### ISSUE TITLE
1000 data point limit

### ISSUE THREAD

**Issue by praveen12bnitt** [ankane/trend-api#1]
I noticed that we have a hard limit of 1000 data points. Is this a hard limit? If i deploy the docker container on a powerful machine can i increase this limit ?

**Comment by ankane** [comment]
Hey @praveen12bnitt, the limit is only there to make sure a single request doesn't monopolize resources for an extended period of time. You should be able to increase it as needed.

R / Plumber (the web server) are single-threaded, so only one request can be processed at a time (no matter how many cores the machine has). If you need higher throughput, you'll probably want to deploy multiple containers and put a load balancer in front of them.

**Comment by praveen12bnitt** [comment]
Thanks @ankane . I understood the reason for the limitation now. We are planning to deploy this in a kube cluster so I can create multiple containers as needed. Thanks for ur help.

**Comment by ankane** [comment]
👍
